apiVersion: v1
kind: Service
metadata:
  name: app2-nginx-service
    labels:
    app: app2-nginx
spec:
  type: NodePort
  selector:
    app: app2-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50000