apiVersion: v1
kind: Service
metadata:
  name: app2-nginx-service
    labels:
    app: app2-nginx
spec:
  type: NodePort
  selector:
    app: app2-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007